on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch all branches
        run: git fetch --all --tags
      
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=$(echo "$raw" | grep -oP '(?<=origin/).*')
          echo "Branch: $branch"
          echo "BRANCH=$branch" >> $GITHUB_ENV
