on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch all branches and tags
        run: git fetch --all --tags
      
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=$(echo "$raw" | grep -oP '(?<=origin/).*')
          if [ -z "$branch" ]; then
            echo "No branch found for tag ${GITHUB_REF#refs/tags/}."
            exit 1
          fi
          echo "Branch: $branch"
          echo "BRANCH=$branch" >> $GITHUB_ENV
