name: Semantic Versioning and Docker Build/Push

on:
  push:
    branches:
      - 'development'

jobs:
  version_and_docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install semver
      run: |
        sudo npm install -g semver
      
    - name: Extract version from branch name
      id: extract_version
      run: echo ::set-output name=version::${GITHUB_REF#refs/heads/}
      
    - name: Determine version increment
      id: determine_version_increment
      run: |
        echo "::set-output name=increment::patch"
    
    - name: Increment version
      id: increment_version
      run: |
        version=$(echo ${{ steps.extract_version.outputs.version }})
        increment=$(echo ${{ steps.determine_version_increment.outputs.increment }})
        new_version=$(semver bump $increment $version)
        echo "::set-output name=new_version::$new_version"
      
    # Rest of your steps...
